Add Git hooks
Julian/lftim pull request #5
Opened 2022-01-10 13:50 UTC by huynhtrankhanh

2022-01-10 13:57 UTC, arthurpaulino commented on git-hooks/pre-commit
> +python3 lean2md.py lean _posts
This is nice. We also need `git add _posts` right after that so the changes will be committed. Does it work?

2022-01-10 18:38 UTC, arthurpaulino commented on git-hooks/pre-commit
> +python3 lean2md.py lean _posts
Oh I just tested. It works!
```suggestion
python3 lean2md.py lean _posts
git add _posts
```

2022-01-10 18:44 UTC, arthurpaulino requested changes

2022-01-10 18:44 UTC, arthurpaulino commented on README.md
> +git config core.hooksPath ./git-hooks
```suggestion
$ git config core.hooksPath ./git-hooks
$ chmod +x ./git-hooks/pre-commit
```

2022-01-10 18:44 UTC, arthurpaulino commented on README.md
> +This repository contains a precommit hook to automatically convert Lean source files to Markdown files on commit. If you want to use this hook, run
```suggestion
This repository contains a pre-commit hook to automatically convert Lean source files to Markdown files on commit. If you want to use this hook, run
```

2022-01-10 18:44 UTC, arthurpaulino commented on git-hooks/pre-commit
> +python3 lean2md.py lean _posts
I just tested it and it works!!
```suggestion
python3 lean2md.py lean _posts
git add _posts
```

2022-01-10 19:57 UTC, Julian commented
I was expecting it'd be pretty trivial to do this with GH Actions (and I believe it would be), so I'm not sure it's worth doing this "longer term" given that GH Actions can just regenerate stuff for us on push, but if you folks want it feel free to merge whenever satisfied.

2022-01-10 20:11 UTC, arthurpaulino commented
@Julian do you mean making something (some GitHub bot?) commit the MD files on top of every push?

There's some advantage to seeing the markdown file on the files changed tab of the PRs though

2022-01-10 20:14 UTC, Julian commented
Yeah. Said bot could push to the same branch so it'd show up on the review

2022-01-10 20:20 UTC, arthurpaulino commented
Oh, I've never configured anything like that. If you know how to do it then I think it's definitely an even cleaner solution!

2022-01-10 20:26 UTC, arthurpaulino commented
The trade-off is: we'll need to pull everytime the bot commits if we want to change something. Do you think it's an issue? Sounds a bit annoying to me

2022-01-10 21:08 UTC, Julian commented
Merge as is and we can always change I think

2022-01-11 00:49 UTC, arthurpaulino commented
I probably misunderstood Julian's idea, but the way that [Eric explained](https://leanprover.zulipchat.com/#narrow/stream/113489-new-members/topic/Lean.20for.20the.20Inept.20Mathematician/near/267518975) it looks good.

We wouldn't need to store lean and markdown files of the same post.

2022-01-11 14:05 UTC, merged